using 'template.bicep'

var prefix = readEnvironmentVariable('RESOURCE_PREFIX')
var sanitizedPrefix = replace(prefix, '-', '')
// Set to 'prod' or 'test'; controls app plan, DB and storage SKUs. Defaults to 'prod'.
param environment = 'prod'
param apiImageName = 'api'
param apiInternalUrl = '${prefix}-api.azurewebsites.net'
param apiUrl = environment == 'test' ? 'https://testikerrokantasi-api.turku.fi' : 'https://kerrokantasi-api.turku.fi'
param apiWebAppName = '${prefix}-api'
param uiImageName = 'ui'
param uiUrl = environment == 'test' ? 'https://testikerrokantasi.turku.fi' : 'https://kerrokantasi.turku.fi'
param uiWebAppName = '${prefix}-ui'
param appInsightsName = '${prefix}-appinsights'
param cacheName = '${prefix}-cache'
param containerRegistryName = '${sanitizedPrefix}registry'
param dbName = 'kerrokantasi'
param dbServerName = '${prefix}-db'
param dbAdminUsername = 'turkuadmin'
param dbUsername = 'kerrokantasi'
param keyvaultName = '${sanitizedPrefix}kv'
param serverfarmPlanName = 'serviceplan'
param storageAccountName = '${sanitizedPrefix}st'
param apiOutboundIpName = environment == 'test' ? 'turku-test-kerrokantasi-outbound-ip' : 'turku-prod-kerrokantasi-outbound-ip'
param natGatewayName = '${prefix}-nat'
param vnetName = '${prefix}-vnet'
param workspaceName = '${prefix}-workspace'
param openIdClientId = environment == 'test' ? '4b872185-8b54-4e10-b3e1-125fcd0fa0f6' : 'kerrokantasi_48790e4c-a91c-431f-9142-daf041d77b2e'
param openIdAudience = 'https://auth.turku.fi/kerrokantasi'
param openIdAuthority = environment == 'test' ? 'https://testitunnistamo.turku.fi/openid' : 'https://tunnistamo.turku.fi/openid'
param openIdApiTokenUrl = environment == 'test' ? 'https://testitunnistamo.turku.fi/api-tokens/' : 'https://tunnistamo.turku.fi/api-tokens/'
param goforeHelsinki = '81.175.255.179'
param goforeTampere = '82.141.89.43'
param goforeVpn = '80.248.248.85'

