# Generated by Django 2.2.12 on 2021-02-15 11:38

import django.contrib.gis.db.models.fields
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0053_auto_20200813_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hearing',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326, verbose_name='area geometry'),
        ),
    ]
